<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.JwkjB0U.App\Entity\UnavailablePeriod' shared service.

include_once $this->targetDirs[3].'/src/Entity/UnavailablePeriod.php';

return $this->privates['.errored..service_locator.JwkjB0U.App\\Entity\\UnavailablePeriod'] = new \App\Entity\UnavailablePeriod();
