<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.G3Dsh9s' shared service.

return $this->privates['.service_locator.G3Dsh9s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'client' => ['privates', '.errored..service_locator.G3Dsh9s.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.G3Dsh9s": it references class "App\\Entity\\Client" but no such service exists.'],
], [
    'client' => 'App\\Entity\\Client',
]);
