<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eH1R0Zw' shared service.

return $this->privates['.service_locator.eH1R0Zw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reservation' => ['privates', '.errored..service_locator.eH1R0Zw.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.eH1R0Zw": it references class "App\\Entity\\Reservation" but no such service exists.'],
], [
    'reservation' => 'App\\Entity\\Reservation',
]);
