<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1sVfNg4' shared service.

return $this->privates['.service_locator.1sVfNg4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'owner' => ['privates', '.errored..service_locator.1sVfNg4.App\\Entity\\Owner', NULL, 'Cannot autowire service ".service_locator.1sVfNg4": it references class "App\\Entity\\Owner" but no such service exists.'],
], [
    'owner' => 'App\\Entity\\Owner',
]);
