<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KJS4slK' shared service.

return $this->privates['.service_locator.KJS4slK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ownerRepository' => ['privates', 'App\\Repository\\OwnerRepository', 'getOwnerRepositoryService.php', true],
], [
    'ownerRepository' => 'App\\Repository\\OwnerRepository',
]);
