<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BPeAJFx' shared service.

return $this->privates['.service_locator.BPeAJFx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService.php', true],
], [
    'regionRepository' => 'App\\Repository\\RegionRepository',
]);
