<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Gn3oxQ2.App\Entity\Comment' shared service.

include_once $this->targetDirs[3].'/src/Entity/Comment.php';

return $this->privates['.errored..service_locator.Gn3oxQ2.App\\Entity\\Comment'] = new \App\Entity\Comment();
