<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vIHt.Cx' shared service.

return $this->privates['.service_locator.vIHt.Cx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'region' => ['privates', '.errored..service_locator.vIHt.Cx.App\\Entity\\Region', NULL, 'Cannot autowire service ".service_locator.vIHt.Cx": it references class "App\\Entity\\Region" but no such service exists.'],
], [
    'region' => 'App\\Entity\\Region',
]);
