<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QX9k4Gx' shared service.

return $this->privates['.service_locator.QX9k4Gx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'unavailablePeriodRepository' => ['privates', 'App\\Repository\\UnavailablePeriodRepository', 'getUnavailablePeriodRepositoryService.php', true],
], [
    'unavailablePeriodRepository' => 'App\\Repository\\UnavailablePeriodRepository',
]);
