<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Vich\UploaderBundle\Naming\SmartUniqueNamer' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Naming/NamerInterface.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Naming/SmartUniqueNamer.php';

return $this->services['Vich\\UploaderBundle\\Naming\\SmartUniqueNamer'] = new \Vich\UploaderBundle\Naming\SmartUniqueNamer();
