<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtVaNGz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtVaNGz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYtVaNGz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYtVaNGz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYtVaNGz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YtVaNGz',
    'container.build_id' => '0a49ca7b',
    'container.build_time' => 1574677219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtVaNGz');
