<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaQMU1W\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaQMU1W/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaQMU1W.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaQMU1W\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNaQMU1W\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NaQMU1W',
    'container.build_id' => 'ec0aaeda',
    'container.build_time' => 1574785060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaQMU1W');
