<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFoBwj9J\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFoBwj9J/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFoBwj9J.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFoBwj9J\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFoBwj9J\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FoBwj9J',
    'container.build_id' => 'c7da651f',
    'container.build_time' => 1574721636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFoBwj9J');
